project:
  type: website
  #output-dir: _site
  output-dir: docs

website:
  title: "Micah's Mechanistic Interpretability Research"
  site-url: https://themicahadler.github.io/blog
  navbar:
    logo: images/logo.png
    # left: []              # either leave this line out, or keep it as []
    right:
      - icon: linkedin
        aria-label: LinkedIn
        href: https://www.linkedin.com/in/micah-adler-9482188/
  favicon: images/favicon.png

format:
  html:
    theme: cosmo
    toc: false
    html-math-method: katex
    code-link: true
    page-layout: article

freeze: auto

execute:
  echo: false
